### ISSUE TITLE
Inquiries

### ISSUE THREAD

**Issue by IIcloudBob** [Normolo/oogahacks#2]
Which injector was used to create this?

First , I advise the use of Infinite Yield over Infinite Admin, due to the fact that it is superior by a lot of factors including 

1.  The amount of commands
2.  The quality of those commands

Secondly, I don't get why you added "Credit goes to their respective owners" if you aren't actually going to credit the owners

**Comment by Normolo** [comment]
The injector used was KRNL, secondly, we do indeed use Infinite Yield, infinite admin is just there to explain it to people who may not be aware of what Infinite Yield does. In regards of your other question, most of them are my work, thus there is no reason to credit the two poeple that helped me code this

**Comment by IIcloudBob** [comment]
"most of them are my work"

You should credit them, even if they didn't do much work. If you paid them then there is no need, but if you didn't then it's morally just to credit them

**Comment by Normolo** [comment]
Commit 0e2ebfa should have taken care of this
